name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: cd HRV\ Monitor
      - uses: mxcl/xcodebuild@v1
